@startuml
class Server
class ServerConnection
class User
interface Command
class ClientSession
class SendMessage extends Command
class Login extends Command
class Logout extends Command
class SendFile extends Command

Server - ServerConnection
ClientSession - Server
ClientSession -- User
ClientSession -- Command

@enduml
