@startuml

class ResponseParser extends Thread {
    +readResponse(Response resp)
}

class Client {
    +listOnline: Set<String>
    +chatLog: Map<String, List<String>>
    sendRequest(Request req)
    getResponse()
}

class ClientConnection {
    -conn: Socket
    -oos: ObjectOutputStream
    -ois: ObjectInputStream
    send(Object obj)
    receive()
    isOn()
    shutdown()
}

Client - ClientConnection
ResponseParser - Client

@enduml
