@startuml

(*) --> "Client.main"
if "new Server.ServerConnection" 
    --> [success] "new ClientSession(socket).start()"
    --> "Login"
    if "Donnee entrer valide"
        --> [true] "Reponse(succes)"
        --> (*)
    else 
        --> [false] "Reponse(refuser)"
        --> (*)
    endif
else 
    --> [fail] "Message d'erreur"
    --> [fin du processus] (*)
endif
@enduml
